name: Socket Security Analysis
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 */6 * * *'  
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Socket Security Analysis
        uses: socket-security/socket-check-action@latest
        with:
          token: ${{ secrets.SOCKET_TOKEN }}
          severity-cutoff: moderate
          
      - name: Run Custom Socket Analysis
        run: |
          # Install Socket CLI
          npm install -g @socket.dev/cli
          
          # Authenticate with Socket
          echo "${{ secrets.SOCKET_TOKEN }}" | socket auth
          
          # Run dependency analysis
          socket dependency-analysis ./package.json > dependency-report.json
          
          # Custom analysis using Socket API and jq
          curl -H "Authorization: Bearer ${{ secrets.SOCKET_TOKEN }}" \
               "https://api.socket.dev/v0/packages/npm/analysis?name=${PACKAGE_NAME}" | \
          jq -r '.issues[] | select(.severity >= 2)' > high-severity-issues.json
          
      - name: Process Results
        run: |
          if [ -s high-severity-issues.json ]; then
            echo "High severity issues found"
            cat high-severity-issues.json
            exit 1
          fi
          
      - name: Create Issue on Detection
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const issues = JSON.parse(fs.readFileSync('high-severity-issues.json', 'utf8'));
            
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.name,
              title: '🚨 Socket Security Issues Detected',
              body: `Security issues found in dependencies:\n\n${JSON.stringify(issues, null, 2)}`
            });

permissions:
  contents: read
  issues: write
